module org.infodavid.commons.restapi {
    exports org.infodavid.commons.restapi.dto;
    exports org.infodavid.commons.restapi.security.filter;
    exports org.infodavid.commons.restapi.annotation;
    exports org.infodavid.commons.restapi.exception;
    exports org.infodavid.commons.restapi.security;
    exports org.infodavid.commons.restapi.controller;
    exports org.infodavid.commons.restapi.security.handler;
    exports org.infodavid.commons.restapi.socket;
    exports org.infodavid.commons.restapi;
    exports org.infodavid.commons.restapi.mapper;
    exports org.infodavid.commons.restapi.configuration;

    opens org.infodavid.commons.restapi.dto to spring.core, org.apache.commons.lang3;
    opens org.infodavid.commons.restapi.security.filter to spring.core;
    opens org.infodavid.commons.restapi.annotation to spring.core;
    opens org.infodavid.commons.restapi.exception to spring.core;
    opens org.infodavid.commons.restapi.security to spring.core;
    opens org.infodavid.commons.restapi.controller to spring.core;
    opens org.infodavid.commons.restapi.security.handler to spring.core;
    opens org.infodavid.commons.restapi.socket to spring.core;
    opens org.infodavid.commons.restapi to spring.core;
    opens org.infodavid.commons.restapi.mapper to spring.core;
    opens org.infodavid.commons.restapi.configuration to spring.core;

    requires transitive com.fasterxml.jackson.annotation;
    requires transitive com.fasterxml.jackson.core;
    requires transitive com.fasterxml.jackson.databind;
    requires transitive cors.filter;
    requires transitive jakarta.annotation;
    requires transitive java.compiler;
    requires transitive java.logging;
    requires transitive jakarta.persistence;
    requires transitive jakarta.validation;
    requires transitive json.sanitizer;
    requires transitive org.apache.commons.collections4;
    requires transitive org.apache.commons.io;
    requires transitive org.apache.commons.lang3;
    requires transitive org.apache.tomcat.embed.core;
    requires transitive org.infodavid.commons.model;
    requires transitive org.infodavid.commons.net;
    requires transitive org.infodavid.commons.persistence;
    requires transitive org.infodavid.commons.service;
    requires transitive org.infodavid.commons.util;
    requires transitive org.mapstruct;
    requires transitive org.slf4j;
    requires transitive spring.beans;
    requires transitive spring.context;
    requires transitive spring.core;
    requires transitive spring.data.commons;
    requires transitive spring.jcl;
    requires transitive spring.messaging;
    requires transitive spring.security.config;
    requires transitive spring.security.core;
    requires transitive spring.security.web;
    requires transitive spring.web;
    requires transitive spring.webmvc;
    requires transitive spring.websocket;
    requires jjwt.api;
}