SET DATABASE COLLATION "French 2";

-- configuration_properties
DROP TABLE IF EXISTS configuration_properties;
DROP SEQUENCE IF EXISTS sq_configuration_properties;
CREATE SEQUENCE sq_configuration_properties START WITH 1;
CREATE TABLE IF NOT EXISTS configuration_properties (
  id BIGINT GENERATED BY DEFAULT AS SEQUENCE sq_configuration_properties PRIMARY KEY,
  archiving_date DATETIME NULL,
  deletable BOOLEAN DEFAULT true,
  read_only BOOLEAN DEFAULT false,
  name VARCHAR(48) NOT NULL,
  data VARCHAR(1024) DEFAULT NULL,
  creation_date DATETIME NOT NULL,
  modification_date DATETIME NOT NULL,
  data_type VARCHAR(48) NOT NULL,
  data_type_def varchar(255) DEFAULT NULL,
  scope varchar(48) DEFAULT NULL,
  label varchar(128) DEFAULT NULL,
  mini double DEFAULT NULL,
  maxi double DEFAULT NULL,
  default_data varchar(1024) DEFAULT NULL,
  CONSTRAINT unq_configuration_properties UNIQUE (name,scope)
);

CREATE INDEX idx_configuration_properties_archiving_date ON configuration_properties (archiving_date);
CREATE INDEX idx_configuration_properties_deletable ON configuration_properties (deletable);
CREATE INDEX idx_configuration_properties_read_only ON configuration_properties (read_only);
CREATE INDEX idx_configuration_properties_name ON configuration_properties (name);
CREATE INDEX idx_configuration_properties_type ON configuration_properties (data_type);
CREATE INDEX idx_configuration_properties_scope ON configuration_properties (scope);

