SET DATABASE COLLATION "French 2";

-- configuration_properties
DROP TABLE IF EXISTS configuration_properties;
DROP SEQUENCE IF EXISTS sq_configuration_properties;
CREATE SEQUENCE sq_configuration_properties START WITH 1;
CREATE TABLE IF NOT EXISTS configuration_properties (
  id BIGINT GENERATED BY DEFAULT AS SEQUENCE sq_configuration_properties PRIMARY KEY,
  archiving_date DATETIME NULL,
  deletable BOOLEAN DEFAULT true,
  read_only BOOLEAN DEFAULT false,
  name VARCHAR(48) NOT NULL,
  data VARCHAR(1024) DEFAULT NULL,
  creation_date DATETIME NOT NULL,
  modification_date DATETIME NOT NULL,
  data_type VARCHAR(48) NOT NULL,
  data_type_def varchar(255) DEFAULT NULL,
  scope varchar(48) DEFAULT NULL,
  label varchar(128) DEFAULT NULL,
  mini double DEFAULT NULL,
  maxi double DEFAULT NULL,
  default_data varchar(1024) DEFAULT NULL,
  CONSTRAINT unq_configuration_properties UNIQUE (name,scope)
);

CREATE INDEX idx_configuration_properties_archiving_date ON configuration_properties (archiving_date);
CREATE INDEX idx_configuration_properties_deletable ON configuration_properties (deletable);
CREATE INDEX idx_configuration_properties_read_only ON configuration_properties (read_only);
CREATE INDEX idx_configuration_properties_name ON configuration_properties (name);
CREATE INDEX idx_configuration_properties_type ON configuration_properties (data_type);
CREATE INDEX idx_configuration_properties_scope ON configuration_properties (scope);

-- users
DROP TABLE IF EXISTS users_properties;
DROP TABLE IF EXISTS users;
DROP SEQUENCE IF EXISTS sq_users;
CREATE SEQUENCE sq_users START WITH 1;
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS SEQUENCE sq_users PRIMARY KEY,
  archiving_date DATETIME NULL,
  deletable BOOLEAN DEFAULT true,
  name VARCHAR(48) NOT NULL,
  display_name VARCHAR(96) NOT NULL,
  creation_date DATETIME NOT NULL,
  modification_date DATETIME NOT NULL,
  connections_count int NOT NULL,
  email VARCHAR(255) DEFAULT NULL,
  expiration_date DATETIME DEFAULT NULL,
  last_connection_date DATETIME NULL,
  last_ip VARCHAR(48) NULL,
  locked BOOLEAN DEFAULT false,
  password VARCHAR(48) NOT NULL,
  roles VARCHAR(512) DEFAULT 'GUEST',
  CONSTRAINT unq_users UNIQUE (name)
);

CREATE INDEX idx_users_archiving_date ON users (archiving_date);
CREATE INDEX idx_users_deletable ON users (deletable);
CREATE INDEX idx_users_name ON users (name);
CREATE INDEX idx_users_displayname ON users (display_name);
CREATE INDEX idx_users_locked ON users (locked);
CREATE INDEX idx_users_email ON users (email);
CREATE INDEX idx_users_lastip ON users (last_ip);

-- users_properties
CREATE TABLE IF NOT EXISTS users_properties (
  user_id BIGINT NOT NULL,
  name VARCHAR(48) NOT NULL,
  read_only BOOLEAN DEFAULT false,
  data VARCHAR(1024) DEFAULT NULL,
  data_type VARCHAR(48) NOT NULL,
  data_type_def varchar(255) DEFAULT NULL,
  scope varchar(48) DEFAULT NULL,
  label varchar(128) DEFAULT NULL,
  mini double DEFAULT NULL,
  maxi double DEFAULT NULL,
  default_data varchar(1024) DEFAULT NULL,
  CONSTRAINT fk_usersproperties_users FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT unq_usersproperties UNIQUE (user_id,name)
);
