SET DATABASE COLLATION "French 2";

-- configuration_properties
DROP TABLE IF EXISTS configuration_properties;
DROP SEQUENCE IF EXISTS sq_configuration_properties;
CREATE SEQUENCE sq_configuration_properties START WITH 1;
CREATE TABLE IF NOT EXISTS configuration_properties (
  id BIGINT GENERATED BY DEFAULT AS SEQUENCE sq_configuration_properties PRIMARY KEY,
  application VARCHAR(96) NOT NULL,
  deletable BOOLEAN DEFAULT true,
  read_only BOOLEAN DEFAULT false,
  name VARCHAR(48) NOT NULL,
  data VARCHAR(1024) DEFAULT NULL,
  creation_date DATETIME NOT NULL,
  modification_date DATETIME NOT NULL,
  data_type VARCHAR(48) NOT NULL,
  data_type_def varchar(255) DEFAULT NULL,
  scope varchar(48) DEFAULT NULL,
  label varchar(128) DEFAULT NULL,
  mini double DEFAULT NULL,
  maxi double DEFAULT NULL,
  default_data varchar(1024) DEFAULT NULL,
  CONSTRAINT unq_configuration_properties UNIQUE (name,scope)
);

CREATE INDEX idx_configuration_properties_deletable ON configuration_properties (deletable);
CREATE INDEX idx_configuration_properties_read_only ON configuration_properties (read_only);
CREATE INDEX idx_configuration_properties_application ON configuration_properties (application);
CREATE INDEX idx_configuration_properties_name ON configuration_properties (name);
CREATE INDEX idx_configuration_properties_type ON configuration_properties (data_type);
CREATE INDEX idx_configuration_properties_scope ON configuration_properties (scope);

-- groups
DROP TABLE IF EXISTS users_groups;
DROP TABLE IF EXISTS groups_properties;
DROP TABLE IF EXISTS groups;
DROP SEQUENCE IF EXISTS sq_groups;
CREATE SEQUENCE sq_groups START WITH 1;
CREATE TABLE IF NOT EXISTS groups (
  id BIGINT GENERATED BY DEFAULT AS SEQUENCE sq_groups PRIMARY KEY,
  name VARCHAR(48) NOT NULL,
  roles VARCHAR(64) NOT NULL,
  description VARCHAR(512) DEFAULT NULL,
  creation_date DATETIME NOT NULL,
  modification_date DATETIME NOT NULL,  
  CONSTRAINT unq_groups UNIQUE (name)
);

CREATE INDEX idx_groups_name ON groups (name);
CREATE INDEX idx_groups_roles ON groups (roles);

-- groups_properties
CREATE TABLE IF NOT EXISTS groups_properties (
  group_id BIGINT NOT NULL,
  name VARCHAR(48) NOT NULL,
  read_only BOOLEAN DEFAULT false,
  data VARCHAR(1024) DEFAULT NULL,
  data_type VARCHAR(48) NOT NULL,
  data_type_def varchar(255) DEFAULT NULL,
  scope varchar(48) DEFAULT NULL,
  label varchar(128) DEFAULT NULL,
  mini double DEFAULT NULL,
  maxi double DEFAULT NULL,
  default_data varchar(1024) DEFAULT NULL,
  CONSTRAINT fk_groups_properties_group FOREIGN KEY (group_id) REFERENCES groups(id) ON DELETE CASCADE,
  CONSTRAINT unq_groups_properties UNIQUE (group_id,name)
);

-- users
DROP TABLE IF EXISTS users_properties;
DROP TABLE IF EXISTS users;
DROP SEQUENCE IF EXISTS sq_users;
CREATE SEQUENCE sq_users START WITH 1;
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS SEQUENCE sq_users PRIMARY KEY,
  name VARCHAR(48) NOT NULL,
  display_name VARCHAR(96) NOT NULL,
  creation_date DATETIME NOT NULL,
  modification_date DATETIME NOT NULL,
  email VARCHAR(255) DEFAULT NULL,
  expiration_date DATETIME DEFAULT NULL,
  last_connection_date DATETIME NULL,
  last_ip VARCHAR(48) NULL,
  locked BOOLEAN DEFAULT false,
  password VARCHAR(48) NOT NULL,
  CONSTRAINT unq_users UNIQUE (name)
);

CREATE INDEX idx_users_name ON users (name);
CREATE INDEX idx_users_displayname ON users (display_name);
CREATE INDEX idx_users_locked ON users (locked);
CREATE INDEX idx_users_email ON users (email);
CREATE INDEX idx_users_lastip ON users (last_ip);

-- users_groups
CREATE TABLE IF NOT EXISTS users_groups (
  user_id BIGINT NOT NULL,
  group_id BIGINT NOT NULL,
  CONSTRAINT fk_users_groups_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT fk_users_groups_group FOREIGN KEY (group_id) REFERENCES groups (id) ON DELETE CASCADE,
  CONSTRAINT unq_users_groups UNIQUE (user_id,group_id)
);

-- users_properties
CREATE TABLE IF NOT EXISTS users_properties (
  user_id BIGINT NOT NULL,
  name VARCHAR(48) NOT NULL,
  read_only BOOLEAN DEFAULT false,
  data VARCHAR(1024) DEFAULT NULL,
  data_type VARCHAR(48) NOT NULL,
  data_type_def varchar(255) DEFAULT NULL,
  scope varchar(48) DEFAULT NULL,
  label varchar(128) DEFAULT NULL,
  mini double DEFAULT NULL,
  maxi double DEFAULT NULL,
  default_data varchar(1024) DEFAULT NULL,
  CONSTRAINT fk_users_properties_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT unq_users_properties UNIQUE (user_id,name)
);
