DROP TABLE IF EXISTS variables;
CREATE TABLE IF NOT EXISTS variables (
  VID int NOT NULL,
  TYPE char(2) NOT NULL,
  NAME varchar(100) NOT NULL,
  VALUE varchar(1024) NOT NULL,
  ECDEF varchar(50) NOT NULL,
  ECMIN varchar(50) NOT NULL,
  ECMAX varchar(50) NOT NULL,
  VALUE_FORMAT char(4) NOT NULL,
  UNITS varchar(50) NOT NULL,
  VALUE_SOURCE varchar(5) NOT NULL,
  EC_PROCESS_ACCESS_ALLOWED varchar(5) NOT NULL
);

INSERT INTO variables (VID, TYPE, NAME, VALUE, ECDEF, ECMIN, ECMAX, VALUE_FORMAT, UNITS, VALUE_SOURCE, EC_PROCESS_ACCESS_ALLOWED) VALUES
  (2, 'EC', 'EstablishCommunicationsTimeout', '5', '10', '5', '600', 'U4', '', '0', 'True'),
  (1, 'EC', 'InitComState', '1', '0', '0', '1', 'U2', '', '0', 'True'),
  (3, 'EC', 'InitControlState', '1', '0', '0', '1', 'U2', '', '0', 'True'),
  (4, 'EC', 'InitOnlineState', '1', '0', '0', '1', 'U2', '', '0', 'True'),
  (5, 'EC', 'InitOfflineState', '0', '0', '0', '2', 'U2', '', '0', 'True'),
  (6, 'EC', 'AttemptOnlineFailure', '0', '0', '0', '1', 'U2', '', '0', 'True'),
  (7, 'SV', 'ControlState', '4', '', '', '', 'U2', '', '0', ''),
  (8, 'SV', 'EventsEnabled', '', '', '', '', 'L', '', '0', ''),
  (9, 'SV', 'Clock', '2015082019191806', '', '', '', 'A', '', '0', ''),
  (10, 'SV', 'AlarmsEnabled', '', '', '', '', 'L', '', '0', ''),
  (11, 'SV', 'AlarmsSet', '', '', '', '', 'L', '', '0', ''),
  (12, 'DV', 'AlarmID', '1', '', '', '', 'U4', '', '0', ''),
  (13, 'EC', 'TimeFormat', '1', '1', '0', '1', 'U1', '', '0', 'True'),
  (15, 'SV', 'ProcessState', '0', '', '', '', 'U1', '', '0', ''),
  (16, 'SV', 'PreviousProcessState', '0', '', '', '', 'U1', '', '0', ''),
  (17, 'DV', 'ECID', '', '', '', '', 'U4', '', '0', ''),
  (19, 'EC', 'HeartBeat', '0', '30', '0', '65535', 'U2', 'seconds', '0', 'True'),
  (20, 'DV', 'PPError', '', '', '', '', 'A', '', '0', ''),
  (21, 'SV', 'PPFormat', '', '', '', '', 'U1', '', '0', ''),
  (22, 'DV', 'PPChangeName', '', '', '', '', 'A', '', '0', ''),
  (23, 'DV', 'PPChangeStatus', '', '', '', '', 'U1', '', '0', ''),
  (24, 'SV', 'PPExecName', '', '', '', '', 'L', '', '0', ''),
  (30, 'DV', 'PortID', '4', '', '', '', 'U1', '', '0', ''),
  (31, 'DV', 'PortTransferState', '2', '', '', '', 'U1', '', '0', ''),
  (32, 'DV', 'PreviousPortTransferState', '0', '', '', '', 'U1', '', '0', ''),
  (33, 'DV', 'LoadPortReservationState', '0', '', '', '', 'U1', '', '0', ''),
  (34, 'DV', 'PreviousLoadPortReservationState', '0', '', '', '', 'U1', '', '0', ''),
  (35, 'DV', 'PortAssociationState', '0', '', '', '', 'U1', '', '0', ''),
  (36, 'DV', 'PreviousPortAssociationState', '0', '', '', '', 'U1', '', '0', ''),
  (40, 'DV', 'SlotMapStatus', '0', '', '', '', 'U1', '', '0', ''),
  (41, 'DV', 'Reason', '0', '', '', '', 'U1', '', '0', ''),
  (50, 'DV', 'CarrierID', '', '', '', '', 'A', '', '0', ''),
  (51, 'DV', 'CarrierType', '', '', '', '', 'A', '', '0', ''),
  (52, 'DV', 'Capacity', '25', '', '', '', 'U1', '', '0', ''),
  (53, 'DV', 'CarrierAccessingStatus', '0', '', '', '', 'U1', '', '0', ''),
  (54, 'DV', 'PreviousCarrierAccessingStatus', '0', '', '', '', 'U1', '', '0', ''),
  (55, 'DV', 'CarrierIDStatus', '3', '', '', '', 'U1', '', '0', ''),
  (56, 'DV', 'PreviousCarrierIDStatus', '1', '', '', '', 'U1', '', '0', ''),
  (57, 'SV', 'CarrierLocationMatrix', '', '', '', '', 'L', '', '0', ''),
  (100, 'EC', 'EnableSpooling', 'True', '', '', '', 'BOOL', '', '0', 'True'),
  (101, 'SV', 'SpoolCountActual', '0', '', '', '', 'U4', '', '0', ''),
  (102, 'SV', 'SpoolCountTotal', '0', '', '', '', 'U4', '', '0', ''),
  (103, 'SV', 'SpoolFullTime', '', '', '', '', 'A', '', '0', ''),
  (104, 'SV', 'SpoolStartTime', '', '', '', '', 'A', '', '0', ''),
  (105, 'EC', 'MaxSpoolTransmit', '0', '10', '0', '100', 'U4', '', '0', 'True'),
  (106, 'EC', 'OverWriteSpool', 'True', '', '', '', 'BOOL', '', '0', 'True'),
  (107, 'SV', 'CurrentSpoolingState', 'Spool_Inactive', '', '', '', 'A', '', '0', 'True'),
  (108, 'SV', 'CurrentSpoolingUnloadState', 'No_Spool_Output', '', '', '', 'A', '', '0', 'True'),
  (109, 'SV', 'CurrentSpoolingLoadState', 'Spool_Not_Full', '', '', '', 'A', '', '0', 'True'),
  (110, 'SV', 'SpoolableMessages', '', '', '', '', 'L', '', '0', 'True'),
  (111, 'SV', 'SpoolAllowedMessages', '', '', '', '', 'L', '', '0', 'True'),
  (112, 'EC', 'SpoolStorageSize', '50', '50', '50', '1000', 'U2', 'Messages', '0', 'True'),
  (113, 'EC', 'WbitS5', 'True', '', '', '', 'BOOL', '', '0', 'True'),
  (114, 'EC', 'L''alarme', 'True', '', '', '', 'BOOL', '', '0', 'True'),
  (200, 'EC', 'SetUpName', 'unknown', '', '', '', 'A', '', '0', 'True'),
  (210, 'DV', 'CurrentProcessTime', '', '', '', '', 'U1', '', '0', ''),
  (-1, 'ED', 'MDLN', 'GEM OEM', '', '', '', '', '', '', ''),
  (-2, 'ED', 'SOFTREV', '1.0', '', '', '', '', '', '', ''),
  (-3, 'ED', 'ConversationTimeout', '30000', '', '', '', '', '', '', '');
